[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  VITE_APP_ENV = "production"

# Production context
[context.production]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy Preview context
[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production", VITE_APP_ENV = "preview" }

# Branch Deploy context
[context.branch-deploy]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production", VITE_APP_ENV = "staging" }

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; font-src 'self' https: data:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 